#!/usr/bin/env python3
"""
4-reorganize-teacher-only-output.py

Reorganize the JSONL file generated by 3-generate-teacher-only.py.

Input format:
    {
        'id': str,
        'input': str (question),
        'responses': [
            {
                'response': str (full response, steps joined by "\n\n"),
                'steps': [...],
                'total_steps': int,
                'total_tokens': int,
                'student_rate': float,   # always 0.0
                'teacher_rate': float    # always 1.0
            },
            ...
        ],
        'student_rate': float,
        'teacher_rate': float,
        'status': str
    }

Output format:
    {
        'input': str (question),
        'output': str (full response)
    }

Processing logic:
    - For each input item, iterate through its responses list
    - Each response generates one output record
    - input field stores the question
    - output field stores the full response text for that response
"""

import json
import argparse
from typing import List, Dict, Any
from tqdm import tqdm
import os


def load_jsonl(file_path: str) -> List[Dict[str, Any]]:
    """Load JSONL file with progress bar"""
    # First, get total line count for progress bar
    print(f"Loading: {file_path}")
    print("Counting total lines...")
    
    total_lines = 0
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                total_lines += 1
    
    print(f"Total lines to read: {total_lines}")
    
    # Now read with progress bar
    data = []
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in tqdm(f, total=total_lines, desc="Reading JSONL", unit="lines"):
            if line.strip():
                try:
                    data.append(json.loads(line.strip()))
                except json.JSONDecodeError as e:
                    print(f"\n[WARNING] Failed to parse line: {e}")
                    continue
    
    print(f"\nLoaded: {len(data)} items")
    return data


def save_jsonl(data: List[Dict], file_path: str):
    """Save data to JSONL file"""
    with open(file_path, 'w', encoding='utf-8') as f:
        for item in data:
            f.write(json.dumps(item, ensure_ascii=False) + '\n')


def reorganize_data(data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Reorganize teacher-only output data.
    
    For each item with responses list, create one output record per response.
    """
    output_data = []
    
    total_items = len(data)
    total_responses = 0
    skipped_items = 0
    total_steps_all = 0
    total_tokens_all = 0
    
    print("\n" + "=" * 60)
    print("Processing teacher-only output data...")
    print("=" * 60)
    
    for item in tqdm(data, desc="Reorganizing", unit="items"):
        item_id = item.get('id', 'Unknown')
        question = item.get('input', '')
        responses = item.get('responses', [])
        item_status = item.get('status', 'unknown')
        
        # Check if this item should be skipped
        if item_status == 'skipped_no_input' or not question or not responses:
            skipped_items += 1
            continue
        
        # Create one output record per response
        for resp_idx, response in enumerate(responses):
            if isinstance(response, dict):
                response_text = response.get('response', '')
                total_steps = response.get('total_steps', 0)
                total_tokens = response.get('total_tokens', 0)
                
                output_record = {
                    'input': question,
                    'output': response_text
                }
                
                output_data.append(output_record)
                total_responses += 1
                total_steps_all += total_steps
                total_tokens_all += total_tokens
    
    print("\n" + "=" * 60)
    print("Processing Statistics:")
    print("=" * 60)
    print(f"  Total input items: {total_items}")
    print(f"  Skipped items: {skipped_items}")
    print(f"  Processed items: {total_items - skipped_items}")
    print(f"  Total output records: {total_responses}")
    if total_items > skipped_items:
        print(f"  Average responses per item: {total_responses / (total_items - skipped_items):.2f}")
    if total_responses > 0:
        print(f"  Average steps per response: {total_steps_all / total_responses:.2f}")
        print(f"  Average tokens per response: {total_tokens_all / total_responses:.1f}")
    print("=" * 60 + "\n")
    
    return output_data


def main():
    parser = argparse.ArgumentParser(
        description="Reorganize 3-generate-teacher-only.py output JSONL file"
    )
    
    parser.add_argument(
        "--input_file", type=str, required=True,
        help="Input JSONL file from 3-generate-teacher-only.py"
    )
    parser.add_argument(
        "--output_file", type=str, required=True,
        help="Output JSONL file with reorganized format"
    )
    
    args = parser.parse_args()
    
    # Verify input file exists
    if not os.path.exists(args.input_file):
        print(f"Error: Input file does not exist: {args.input_file}")
        return
    
    print("=" * 60)
    print("Teacher-Only Output Reorganization")
    print("=" * 60)
    print(f"Input file : {args.input_file}")
    print(f"Output file: {args.output_file}")
    print("=" * 60)
    
    # Load data
    data = load_jsonl(args.input_file)
    if not data:
        print("Error: Input file is empty or cannot be read.")
        return
    
    # Reorganize data
    output_data = reorganize_data(data)
    
    # Save output
    print(f"Saving to: {args.output_file}")
    save_jsonl(output_data, args.output_file)
    print("Successfully saved!")
    
    print("\n" + "=" * 60)
    print("Reorganization Complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
